import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import {
  QueryClient,
  QueryClientProvider,
  useQuery,
} from "@tanstack/react-query";
import Providers from "@/components/Provider";
import Navbar from "@/components/Navbar";

const queryClient = new QueryClient();

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Infintescrolling",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
